{% set name = "zchunk" %}
{% set version = "1.2.2" %}

package:
  name: zchunk-split
  version: {{ version }}

source:
  url: https://github.com/zchunk/zchunk/archive/{{ version }}.tar.gz
  sha256: bc36f13b1bcb2ab52d046bfc3ec04a9bd1f89b070b4e8fca52eded235a583526
  patches:
    - zstd_arg.patch

build:
  number: 1

outputs:
  - name: zchunk
    requirements:
      build:
        - {{ compiler('c') }}
        - meson
        - pkg-config
        - ninja
      host:
        - libcurl
        - zstd
        - openssl
        - argp-standalone  # [osx or win]
      run:
        - libcurl
        - zstd
        - openssl
        - ucrt  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x' ) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libzck${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/bin/zck                 # [unix]
        - test -f ${PREFIX}/include/zck.h           # [unix]
        - test -f ${PREFIX}/lib/pkgconfig/zck.pc    # [unix]
        - if not exist %LIBRARY_PREFIX%\include\zck.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\zck-1.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\zck.exe (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\pkgconfig\zck.pc (exit 1)  # [win]
        - zck --help

  - name: zchunk-static
    requirements:
      build:
        - {{ compiler('c') }}
        - meson
        - pkg-config
        - ninja
      host:
        - {{ pin_subpackage('zchunk', exact=True) }}
        - libcurl
        - zstd
        - openssl
        - argp-standalone  # [osx or win]
      run:
        - {{ pin_subpackage('zchunk', exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libzck.a  # [not win]
        - if not exist %LIBRARY_LIB%\libzck_a.lib exit 1  # [win]

about:
  home: https://github.com/zchunk/zchunk
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A file format designed for highly efficient deltas while maintaining good compression
  description: |
    zchunk is a compressed file format that splits the file into independent
    chunks. This allows you to only download changed chunks when downloading a
    new version of the file, and also makes zchunk files efficient over rsync.

    zchunk files are protected with strong checksums to verify that the file
    you downloaded is, in fact, the file you wanted.

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
