{% set name = "zchunk" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zchunk/zchunk/archive/{{ version }}.tar.gz
  sha256: eb3d531916d6fea399520a2a4663099ddbf2278088599fa09980631067dc9d7b

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - pkg-config  # [osx or win]
    - ninja
  host:
    - libcurl
    - openssl
    - zstd
  run:
    - libcurl
    - openssl
    - zstd

test:
  commands:
    - test -f ${PREFIX}/lib/libzck${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/bin/zck  # [unix]
    - test -f ${PREFIX}/include/zck.h  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/zck.pc  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\zck.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\zck.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\zck.exe exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\zck.h exit 1  # [win]

about:
  home: https://github.com/zchunk/zchunk
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A file format designed for highly efficient deltas while maintaining good compression
  description: |
    zchunk is a compressed file format that splits the file into independent
    chunks. This allows you to only download changed chunks when downloading a
    new version of the file, and also makes zchunk files efficient over rsync.

    zchunk files are protected with strong checksums to verify that the file
    you downloaded is, in fact, the file you wanted.

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
